apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  labels:
    app: pingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
        - name: pingapp
          image: nicopaez/pingapp:2.1.0
          ports:
          - containerPort: 4567
          envFrom:
            - configMapRef:
                name: configmap1
          volumeMounts:
            - name: config-files
              mountPath: /config
            - name: secret-file
              mountPath: /secret
              readOnly: true
      volumes:
        - name: config-files
          configMap:
            name: "configmap2"
            items:
            - key: "config.json"
              path: "config.json"
        - name: secret-file
          secret:
            secretName: "secret1"
            items:
            - key: "secret.json"
              path: "secret.json"